spring:

  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/mogakcote
    username: root
    password: 1234

  data:
    redis:
      host:
      port:
      username:
      password:

  security:
    jwt:
      issuer: "http://localhost:8081"
      secretKey: "c2VjcmV0S2V5c2VjcmV0S2V5c2VjcmV0S2V5c2VjcmV0S2V5"
      access-token-expiration-second: 1800
      refresh-token-expiration-second: 10080
    user:
      password:
        secretKey: "secretKeysecretKeysecretKeysecretKey"
        reset:
          registerTimeoutSecond: 1800
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

logging:
  level:
    web: debug