spring:

  # DB
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      username: ${SPRING_DATA_REDIS_USERNAME}
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}

  security:
    jwt:
      issuer: ${SPRING_SECURITY_JWT_ISSUER}
      secretKey: ${SPRING_SECURITY_JWT_SECRETKEY}
      access-token-expiration-second: 1800
      refresh-token-expiration-second: 10080
    user:
      password:
        secretKey: ${SPRING_SECURITY_USER_PASSWORD_SECRETKEY}
        reset:
          registerTimeoutSecond: 1800

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

logging:
  level:
    org.springframework: DEBUG
    com.zaxxer.hikari: DEBUG