spring:
  application:
    name: mogak-codingtest
  servlet:
    multipart:
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/mogakcote
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 15
      maximum-pool-size: 20
      connection-timeout: 30000 # 30초
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      repositories:
        enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.web: debug
    com.ormi.mogakcote: debug
